-- CreateEnum
CREATE TYPE "AppointmentType" AS ENUM ('CHECKUP', 'CLEANING', 'FILLING', 'EXTRACTION', 'ROOT_CANAL', 'ORTHODONTIC', 'PERIODONTAL', 'PROSTHODONTIC', 'PEDIATRIC', 'EMERGENCY');

-- AlterTable
ALTER TABLE "Appointment" ADD COLUMN     "type" "AppointmentType" NOT NULL DEFAULT 'CHECKUP';
